export const UPDATE_FREQUENCY_LIST = 'UPDATE_FREQUENCY_LIST';
export const UPDATE_WORD_LIST = 'UPDATE_WORD_LIST';
export const UPDATE_EMOJI_LIST = 'UPDATE_EMOJI_LIST';
export const UPDATE_DATA_TYPE = 'UPDATE_DATA_TYPE';
export const UPDATE_VIZ_TYPE = 'UPDATE_VIZ_TYPE';
export const UPDATE_WORDCLOUD_OBJECT = 'UPDATE_WORDCLOUD_OBJECT';