//word
export const UPDATE_FREQUENCY_LIST = 'UPDATE_FREQUENCY_LIST';
export const INITIALIZE_FREQUENCY_LISTS = 'INITIALIZE_FREQUENCY_LISTS';
export const UPDATE_DATA_TYPE = 'UPDATE_DATA_TYPE';
export const UPDATE_VIZ_TYPE = 'UPDATE_VIZ_TYPE';
export const UPDATE_STOPWORDS = 'UPDATE_STOPWORDS';
export const HANDLE_FILTER_APPLY = 'HANDLE_FILTER_APPLY';
export const TOGGLE_STOPWORDS = 'TOGGLE_STOPWORDS';
export const UPDATE_WORDCLOUD_LAYOUT = 'UPDATE_WORDCLOUD_LAYOUT';
export const UPDATE_STYLE = 'UPDATE_STYLE';
export const GET_CHATS_META_DATA_LIST_SUCCESS = 'GET_CHATS_META_DATA_LIST_SUCCESS';

// auth
// export const GET_LEADS = 'GET_LEADS';
// export const DELETE_LEAD = 'DELETE_LEAD';
// export const ADD_LEAD = 'ADD_LEAD';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
// export const USER_LOADING = 'USER_LOADING';
// export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_LEADS = 'CLEAR_LEADS';
export const PING_SUCCESS = 'PING_SUCCESS';
export const PING_FAIL = 'PING_FAIL';
