# Generated by Django 3.0.1 on 2020-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROWID', models.CharField(max_length=150)),
                ('text', models.EmailField(blank=True, max_length=254)),
                ('is_from_me', models.CharField(max_length=50)),
            ],
        ),
    ]
