# Generated by Django 3.2.4 on 2021-06-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0003_auto_20210626_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencylist',
            old_name='frequencyListsDict',
            new_name='frequency_lists_dict',
        ),
        migrations.AddField(
            model_name='frequencylist',
            name='chat_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
