# Generated by Django 3.2.4 on 2021-06-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0004_auto_20210627_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencylist',
            name='chat_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
