# Generated by Django 3.2.4 on 2021-06-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessage', '0005_frequencylist_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencylist',
            name='chat_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
