# Generated by Django 3.2.4 on 2022-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatInternalId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
